services:
  #vuejs:
  # container_name: scrabble-vuejs
  # build:
  #   context: ./vuejs
  #   dockerfile: Dockerfile
  # ports:
  #   - 8080:8080
  api:
    container_name: scrabble-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      FASTAPI_MODE: development
      DB_NAME: scrabble
      DB_USER: alpha
      DB_PASS: alpha
      DB_HOST: 'scrabble-db'
    ports:
      - 8000:8000
    tty: true
    networks:
      - scrawl
    volumes:
      - ./api:/api
  db:
    image: mariadb:latest
    container_name: scrabble-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: scrabble
      MYSQL_USER: alpha
      MYSQL_PASSWORD: alpha
      MYSQL_ROOT_PASSWORD: asdf
    ports:
      - 3310:3306
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - scrawl
networks:
  scrawl:
    driver: bridge
volumes:
  db_data:
  api:
  vuejs:
